// Writes src/vendor/ses.ts: the SES shim (https://github.com/endojs/endo,
// Apache-2.0) from node_modules as a string, which the kernel puts in front
// of the agent's runner bundle. The bundle runs in a gadget's isolate, not in
// the kernel's, so SES is text here, never imported.
//   node scripts/vendor-ses.mjs           write it
//   node scripts/vendor-ses.mjs --check   fail if it is out of date
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const kernel = join(dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(await readFile(join(kernel, "node_modules/ses/package.json"), "utf8"));
const source = await readFile(join(kernel, "node_modules/ses/dist/ses.umd.min.js"), "utf8");
const out = `// Generated by scripts/vendor-ses.mjs from ses ${pkg.version}; do not edit.
// SES (https://github.com/endojs/endo/tree/master/packages/ses) is
// Copyright the Endo contributors and licensed under the Apache License 2.0.
export const SES_VERSION = ${JSON.stringify(pkg.version)};
export const SES_SOURCE = ${JSON.stringify(source)};
`;
const target = join(kernel, "src/vendor/ses.ts");
if (process.argv.includes("--check")) {
  const current = await readFile(target, "utf8").catch(() => "");
  if (current !== out) {
    console.error("src/vendor/ses.ts is out of date: run node scripts/vendor-ses.mjs");
    process.exit(1);
  }
} else {
  await writeFile(target, out);
}
