apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kodo-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kodo-operator
subjects:
  - kind: ServiceAccount
    name: kodo-operator
    namespace: kodo-system
