// Package celldapp turns a Durable Object class of a celld (Wrangler) project
// into a kodo gadget: it bundles the class behind a generated App that
// extends DurableObject, checks the bundle for what a gadget cannot have,
// and writes the gadget as a Blueprint for the operator.
//
// The class runs unchanged. Its constructor gets the cell's state, so
// state.storage is the cell's own database, and an env with no bindings:
// a gadget reaches the outside only through the grants its owner gives it.
// The rest of the Worker, its router and the other classes, is left behind;
// the kernel routes each cell's hostname to its gadget.
package celldapp

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strconv"
	"strings"

	"github.com/evanw/esbuild/pkg/api"
)

// Project is the part of a Wrangler config a gadget is built from.
type Project struct {
	Dir     string
	Name    string `json:"name"`
	Main    string `json:"main"`
	Durable struct {
		Bindings []struct {
			Name   string `json:"name"`
			Class  string `json:"class_name"`
			Script string `json:"script_name"`
		} `json:"bindings"`
	} `json:"durable_objects"`
}

// Load reads the Wrangler config at path, a wrangler.jsonc or wrangler.json
// or the directory that holds one.
func Load(path string) (*Project, error) {
	if info, err := os.Stat(path); err == nil && info.IsDir() {
		for _, name := range []string{"wrangler.jsonc", "wrangler.json"} {
			if _, err := os.Stat(filepath.Join(path, name)); err == nil {
				path = filepath.Join(path, name)
				break
			}
		}
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var p Project
	if err := json.Unmarshal(stripJSONC(data), &p); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	if p.Main == "" {
		return nil, fmt.Errorf("%s: no main module", path)
	}
	p.Dir = filepath.Dir(path)
	return &p, nil
}

// Classes are the project's own Durable Object classes, in config order.
func (p *Project) Classes() []string {
	var classes []string
	for _, b := range p.Durable.Bindings {
		if b.Script == "" && !slices.Contains(classes, b.Class) {
			classes = append(classes, b.Class)
		}
	}
	return classes
}

// Class picks the class to build: the one named, or the only one.
func (p *Project) Class(name string) (string, error) {
	classes := p.Classes()
	switch {
	case name != "" && slices.Contains(classes, name):
		return name, nil
	case name != "":
		return "", fmt.Errorf("%s has no Durable Object class %s; it has %s", p.Name, name, strings.Join(classes, ", "))
	case len(classes) == 1:
		return classes[0], nil
	case len(classes) == 0:
		return "", fmt.Errorf("%s has no Durable Object classes", p.Name)
	default:
		return "", fmt.Errorf("%s has several Durable Object classes, pick one: %s", p.Name, strings.Join(classes, ", "))
	}
}

// entry is the generated module: an App that extends DurableObject, which
// celld requires of a facet, around the original class. Its env throws on
// any binding, so a class that reaches for one fails with a reason.
const entry = `import { DurableObject } from "cloudflare:workers";
import { %[1]s as Original } from %[2]s;

const env = new Proxy({}, {
  get(_, key) {
    if (typeof key === "symbol") return undefined;
    throw new Error("env." + key + " is not available in a kodo gadget; it reaches the outside through capability grants");
  },
});

// Generated by kodo publish: the celld Durable Object class %[1]s as a kodo gadget.
export class App extends DurableObject {
  #inner;
  constructor(ctx, _env) {
    super(ctx, _env);
    this.#inner = new Original(ctx, env);
  }
  fetch(request) {
    return this.#inner.fetch(request);
  }
}
`

// Build bundles class as a gadget module and checks it. A bundle that fails
// the checks is returned with the problems, as an error.
func (p *Project) Build(class string) ([]byte, error) {
	main, err := filepath.Abs(filepath.Join(p.Dir, p.Main))
	if err != nil {
		return nil, err
	}
	result := api.Build(api.BuildOptions{
		Stdin: &api.StdinOptions{
			Contents:   fmt.Sprintf(entry, class, strconv.Quote(filepath.ToSlash(main))),
			ResolveDir: p.Dir,
			Sourcefile: "gadget-entry.js",
		},
		Bundle:     true,
		Format:     api.FormatESModule,
		Platform:   api.PlatformBrowser,
		Target:     api.ES2024,
		Conditions: []string{"workerd", "worker", "browser"},
		Plugins:    []api.Plugin{runtimeModules},
		Metafile:   true,
		LogLevel:   api.LogLevelSilent,
		Write:      false,
	})
	if len(result.Errors) > 0 {
		msgs := api.FormatMessages(result.Errors, api.FormatMessagesOptions{Kind: api.ErrorMessage})
		hint := ""
		if strings.Contains(strings.Join(msgs, ""), "Could not resolve") {
			hint = "\n(install the project's dependencies first, e.g. npm install in " + p.Dir + ")"
		}
		return nil, fmt.Errorf("bundling %s: %s%s", class, strings.Join(msgs, ""), hint)
	}
	bundle := result.OutputFiles[0].Contents
	if problems := check(bundle, result.Metafile); len(problems) > 0 {
		return bundle, &Unsupported{Class: class, Problems: problems}
	}
	return bundle, nil
}

// runtimeModules leaves cloudflare:* and node:* imports to the runtime, as
// free of side effects: an import only another class of the Worker uses is
// dropped with that class, so the checks see only what this one imports.
var runtimeModules = api.Plugin{
	Name: "runtime-modules",
	Setup: func(build api.PluginBuild) {
		build.OnResolve(api.OnResolveOptions{Filter: `^(cloudflare|node):`}, func(args api.OnResolveArgs) (api.OnResolveResult, error) {
			return api.OnResolveResult{Path: args.Path, External: true, SideEffects: api.SideEffectsFalse}, nil
		})
	},
}

// Unsupported lists what keeps a class from running as a gadget.
type Unsupported struct {
	Class    string
	Problems []string
}

func (u *Unsupported) Error() string {
	return fmt.Sprintf("%s cannot run as a kodo gadget:\n  - %s", u.Class, strings.Join(u.Problems, "\n  - "))
}

var (
	// env.NAME and this.env.NAME, but not process.env.NAME, which bundled
	// libraries read and which is simply absent in a gadget.
	envUse       = regexp.MustCompile(`(?:\bthis\.|[^.\w$])env\??\.([A-Za-z_$][\w$]*)`)
	alarmUse     = regexp.MustCompile(`\.(?:setAlarm|getAlarm|deleteAlarm)\(`)
	websocketUse = regexp.MustCompile(`\.(?:acceptWebSocket|getWebSockets)\(`)
)

// check finds what a gadget does not have: bindings, imports other than
// cloudflare:workers, native alarms and hibernatable WebSockets. Outbound
// fetch is not found here; the kernel refuses it when the gadget runs.
func check(bundle []byte, metafile string) []string {
	var problems []string
	var names []string
	for _, m := range envUse.FindAllSubmatch(bundle, -1) {
		if name := string(m[1]); !slices.Contains(names, name) {
			names = append(names, name)
		}
	}
	if len(names) > 0 {
		problems = append(problems, fmt.Sprintf("uses env.%s; a gadget has no bindings or secrets, and reaches services through capability grants (a model: inference:model/<name>:invoke)", strings.Join(names, ", env.")))
	}
	for _, imp := range externalImports(metafile) {
		if imp != "cloudflare:workers" {
			problems = append(problems, fmt.Sprintf("imports %s, which a gadget does not have", imp))
		}
	}
	if alarmUse.Match(bundle) {
		problems = append(problems, "uses storage alarms; a gadget asks its cell with this.setAlarm() from the kodo Gadget class")
	}
	if websocketUse.Match(bundle) {
		problems = append(problems, "accepts WebSockets; with the kodo Gadget class the cell holds the sockets, and a gadget gets onOpen() and onMessage() and sends with this.send() and this.broadcast()")
	}
	return problems
}

func externalImports(metafile string) []string {
	var meta struct {
		Outputs map[string]struct {
			Imports []struct {
				Path     string `json:"path"`
				External bool   `json:"external"`
			} `json:"imports"`
		} `json:"outputs"`
	}
	if err := json.Unmarshal([]byte(metafile), &meta); err != nil {
		return nil
	}
	var imports []string
	for _, out := range meta.Outputs {
		for _, imp := range out.Imports {
			if imp.External && !slices.Contains(imports, imp.Path) {
				imports = append(imports, imp.Path)
			}
		}
	}
	slices.Sort(imports)
	return imports
}

// Blueprint is where and as what a gadget is published.
type Blueprint struct {
	Name      string
	Version   string
	Fleet     string
	Namespace string
}

var (
	nameRE    = regexp.MustCompile(`^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$`)
	versionRE = regexp.MustCompile(`^[0-9a-z][0-9a-z.-]{0,40}$`)
)

// Validate checks the name and version against the kernel's rules, and the
// version against what fits a Kubernetes object name.
func (b Blueprint) Validate() error {
	var errs []error
	if !nameRE.MatchString(b.Name) {
		errs = append(errs, fmt.Errorf("blueprint name %q: lowercase letters, digits and inner hyphens, at most 63", b.Name))
	}
	if !versionRE.MatchString(b.Version) {
		errs = append(errs, fmt.Errorf("version %q: lowercase letters, digits, dots and hyphens, e.g. 0.1.0", b.Version))
	}
	if b.Fleet == "" {
		errs = append(errs, errors.New("fleet is required"))
	}
	return errors.Join(errs...)
}

// Object is the name of the Blueprint object and of its source ConfigMap.
// Each version has its own ConfigMap, as a version's source never changes.
func (b Blueprint) Object() string { return b.Name + "-" + b.Version }

// DefaultName is the Blueprint name for class of the project: the Worker's
// name and the class, e.g. celld-do-lab-counter.
func (p *Project) DefaultName(class string) string {
	return strings.Trim(nonName.ReplaceAllString(strings.ToLower(p.Name+"-"+class), "-"), "-")
}

var nonName = regexp.MustCompile(`[^a-z0-9]+`)

// Write puts the gadget, its Blueprint and a kustomization in dir, ready for
// kubectl apply -k.
func (b Blueprint) Write(dir string, bundle []byte) error {
	if err := b.Validate(); err != nil {
		return err
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	files := map[string][]byte{
		"gadget.js":          bundle,
		"blueprint.yaml":     b.manifest(),
		"kustomization.yaml": b.kustomization(),
	}
	for name, data := range files {
		if err := os.WriteFile(filepath.Join(dir, name), data, 0o644); err != nil {
			return err
		}
	}
	return nil
}

func (b Blueprint) manifest() []byte {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, `# Generated by kodo publish.
apiVersion: kodo.dev/v1alpha1
kind: Blueprint
metadata:
  name: %[1]s
  namespace: %[2]s
spec:
  fleet: %[3]s
  blueprint: %[4]s
  version: %[5]q
  source:
    name: %[1]s
    key: gadget.js
`, b.Object(), b.Namespace, b.Fleet, b.Name, b.Version)
	return buf.Bytes()
}

func (b Blueprint) kustomization() []byte {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, `# Generated by kodo publish.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: %[1]s
resources:
  - blueprint.yaml
configMapGenerator:
  - name: %[2]s
    files:
      - gadget.js
generatorOptions:
  disableNameSuffixHash: true
`, b.Namespace, b.Object())
	return buf.Bytes()
}

// stripJSONC removes comments and trailing commas, outside strings.
func stripJSONC(data []byte) []byte {
	var out []byte
	for i := 0; i < len(data); i++ {
		c := data[i]
		switch {
		case c == '"':
			j := i + 1
			for ; j < len(data) && data[j] != '"'; j++ {
				if data[j] == '\\' {
					j++
				}
			}
			out = append(out, data[i:min(j+1, len(data))]...)
			i = j
		case c == '/' && i+1 < len(data) && data[i+1] == '/':
			for i < len(data) && data[i] != '\n' {
				i++
			}
			i--
		case c == '/' && i+1 < len(data) && data[i+1] == '*':
			end := bytes.Index(data[i+2:], []byte("*/"))
			if end < 0 {
				return out
			}
			i += end + 3
		case c == ',':
			j := i + 1
			for j < len(data) && strings.ContainsRune(" \t\r\n", rune(data[j])) {
				j++
			}
			if j < len(data) && (data[j] == '}' || data[j] == ']') {
				continue
			}
			out = append(out, c)
		default:
			out = append(out, c)
		}
	}
	return out
}
